<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-28T12:33:35 IST" name="Suite" finished-at="2024-10-28T12:34:21 IST" duration-ms="46685">
    <groups>
      <group name="Purchase">
        <method signature="Main.order(java.util.HashMap)[pri:0, instance:Website.E_commerce.Main@1b955cac]" name="order" class="Website.E_commerce.Main"/>
      </group> <!-- Purchase -->
      <group name="ErrorValidation_ProductValidation">
        <method signature="ErrorValidation.ProductValidation()[pri:0, instance:Website.E_commerce.ErrorValidation@61a88b8c]" name="ProductValidation" class="Website.E_commerce.ErrorValidation"/>
      </group> <!-- ErrorValidation_ProductValidation -->
      <group name="ErrorValidation_LoginValidation">
        <method signature="ErrorValidation.LoginValidation()[pri:0, instance:Website.E_commerce.ErrorValidation@61a88b8c]" name="LoginValidation" class="Website.E_commerce.ErrorValidation"/>
      </group> <!-- ErrorValidation_LoginValidation -->
    </groups>
    <test started-at="2024-10-28T12:33:35 IST" name="Main Test" finished-at="2024-10-28T12:34:04 IST" duration-ms="29184">
      <class name="Website.E_commerce.Main">
        <test-method signature="order(java.util.HashMap)[pri:0, instance:Website.E_commerce.Main@1b955cac]" started-at="2024-10-28T12:33:35 IST" name="order" data-provider="getData" finished-at="2024-10-28T12:34:04 IST" duration-ms="28938" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchSessionException">
            <message>
              <![CDATA[Tried to run command without establishing a connection
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [b9777954-045d-45d3-91f6-cabe07f0c6b7, screenshot {}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 131.0.2, moz:accessibilityChecks: false, moz:buildID: 20241008210941, moz:geckodriverVersion: 0.35.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 11828, moz:profile: C:\Users\KARUNY~1\AppData\L..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
Session ID: b9777954-045d-45d3-91f6-cabe07f0c6b7]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchSessionException: Tried to run command without establishing a connection
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [b9777954-045d-45d3-91f6-cabe07f0c6b7, screenshot {}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 131.0.2, moz:accessibilityChecks: false, moz:buildID: 20241008210941, moz:geckodriverVersion: 0.35.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 11828, moz:profile: C:\Users\KARUNY~1\AppData\L..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
Session ID: b9777954-045d-45d3-91f6-cabe07f0c6b7
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:591)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:321)
at Website.TestComponents.BaseTest.getScreenshot(BaseTest.java:86)
at Website.TestComponents.Listeners.onTestSuccess(Listeners.java:34)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:112)
at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:263)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:751)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchSessionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- order -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Website.E_commerce.Main@1b955cac]" started-at="2024-10-28T12:33:35 IST" name="launchApplication" finished-at="2024-10-28T12:33:49 IST" duration-ms="13286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="YourOrder()[pri:0, instance:Website.E_commerce.Main@1b955cac]" started-at="2024-10-28T12:34:04 IST" name="YourOrder" finished-at="2024-10-28T12:34:04 IST" depends-on-methods="Website.E_commerce.Main.order" duration-ms="2" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Website.E_commerce.Main.YourOrder() on instance Website.E_commerce.Main@1b955cac depends on not successfully finished methods 
[Website.E_commerce.Main.order() on instance Website.E_commerce.Main@1b955cac]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Website.E_commerce.Main.YourOrder() on instance Website.E_commerce.Main@1b955cac depends on not successfully finished methods 
[Website.E_commerce.Main.order() on instance Website.E_commerce.Main@1b955cac]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- YourOrder -->
      </class> <!-- Website.E_commerce.Main -->
    </test> <!-- Main Test -->
    <test started-at="2024-10-28T12:33:35 IST" name="ErrorValidation Test" finished-at="2024-10-28T12:34:21 IST" duration-ms="46685">
      <class name="Website.E_commerce.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Website.E_commerce.ErrorValidation@61a88b8c]" started-at="2024-10-28T12:33:35 IST" name="launchApplication" finished-at="2024-10-28T12:33:46 IST" duration-ms="11147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginValidation()[pri:0, instance:Website.E_commerce.ErrorValidation@61a88b8c]" started-at="2024-10-28T12:33:46 IST" name="LoginValidation" finished-at="2024-10-28T12:33:46 IST" duration-ms="606" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email and password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email and password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Website.E_commerce.ErrorValidation.LoginValidation(ErrorValidation.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Website.E_commerce.ErrorValidation@61a88b8c]" started-at="2024-10-28T12:33:47 IST" name="closeBrowser" finished-at="2024-10-28T12:33:48 IST" duration-ms="1356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Website.E_commerce.ErrorValidation@61a88b8c]" started-at="2024-10-28T12:33:48 IST" name="launchApplication" finished-at="2024-10-28T12:33:56 IST" duration-ms="7850" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductValidation()[pri:0, instance:Website.E_commerce.ErrorValidation@61a88b8c]" started-at="2024-10-28T12:33:56 IST" name="ProductValidation" finished-at="2024-10-28T12:34:20 IST" duration-ms="23623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Website.E_commerce.ErrorValidation@61a88b8c]" started-at="2024-10-28T12:34:20 IST" name="closeBrowser" finished-at="2024-10-28T12:34:21 IST" duration-ms="1473" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Website.E_commerce.ErrorValidation -->
    </test> <!-- ErrorValidation Test -->
  </suite> <!-- Suite -->
</testng-results>
